---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-data-pvc
  namespace: jupyter-notebook
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi