apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
data:
  data: "proxmox01=192.168.103.200:6789,proxmox02=192.168.103.201:6789,proxmox3=192.168.103.202:6789"
  mapping: "{}"
  maxMonId: "2"
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-mon
  namespace: rook-ceph
type: Opaque
data:
  admin-secret: QVFCMU1qOXBYQXoxR3hBQXdSWVluM0FzaDh0dm1Rei9iUnpWRHc9PQ==
  cluster-name: cm9vay1jZXBoLWV4dGVybmFs
  fsid: ZDc1NmU2MzAtNTMxMC00OGY4LWI1YmEtM2QxOTBkNjYxNjIy
  mon-secret: QVFCMU1qOXBYQXoxR3hBQXdSWVluM0FzaDh0dm1Rei9iUnpWRHc9PQ==
