---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-server-cert
  namespace: n8n
spec:
  secretName: n8n-server-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - n8n.local.perelohome.com