---
apiVersion: v1
kind: Namespace
metadata:
  name: data-analys

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: data-analys
  source:
    repoURL: https://airbytehq.github.io/helm-charts
    chart: airbyte
    targetRevision: 1.9.2
    helm:
      releaseName: airbyte
      values: |
        global:
          edition: community
          airbyteUrl: https://airbyte.apps.okd.pro.perelohome.com
          auth:
            enabled: false
          jobs:
            # Temporary lower resource requests to improve scheduling in constrained clusters.
            resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "1"
                memory: "1Gi"

        ingress:
          enabled: false

        postgresql:
          enabled: true
          podSecurityContext: {}
          containerSecurityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          commonAnnotations: {}

        minio:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: airbyte
  namespace: data-analys
spec:
  host: airbyte.apps.okd.pro.perelohome.com
  to:
    kind: Service
    name: airbyte-airbyte-server-svc
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
