---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: data-analys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: data-analys
spec:
  selector:
    app: metabase
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: metabase
  namespace: data-analys
spec:
  host: metabase.apps.okd.pro.perelohome.com
  to:
    kind: Service
    name: metabase
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None