---
apiVersion: v1
kind: Secret
metadata:
  name: metabase-secrets
  namespace: data-analys
type: Opaque
stringData:
  MB_DB_TYPE: mysql
  MB_DB_DBNAME: metabase
  MB_DB_PORT: "3306"
  MB_DB_USER: metabase
  MB_DB_PASS: change-me-metabase-db-pass
  MB_DB_HOST: mysql.data-analys.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: data-analys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase-app
          image: metabase/metabase:v0.58.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: MB_DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: MB_DB_TYPE
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: MB_DB_DBNAME
            - name: MB_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: MB_DB_PORT
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: MB_DB_USER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: MB_DB_PASS
            - name: MB_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: MB_DB_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: data-analys
spec:
  selector:
    app: metabase
  ports:
    - name: http-web
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: metabase
  namespace: data-analys
spec:
  host: metabase.apps.okd.pro.perelohome.com
  to:
    kind: Service
    name: metabase-service
    weight: 100
  port:
    targetPort: http-web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
