---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-cluster
  namespace: pro-travelroute
spec:
  type: ExternalName
  externalName: mongodb-svc.pro-travelroute.svc.cluster.local
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc-0
  namespace: pro-travelroute
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      nodePort: 32017
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc-1
  namespace: pro-travelroute
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      nodePort: 32018
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc-2
  namespace: pro-travelroute
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      nodePort: 32019
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-2