---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-cluster
  namespace: staging-travelroute
spec:
  type: ExternalName
  externalName: mongodb-svc.staging-travelroute.svc.cluster.local
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
