---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
  namespace: plex-server
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: linuxserver/jellyfin:latest
          ports:
          - name: jellyfin
            containerPort: 8096
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: plex-series
              mountPath: /series
            - name: plex-movies
              mountPath: /movies
            - name: plex-courses
              mountPath: /courses
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-pvc-config
        - name: plex-series
          persistentVolumeClaim:
            claimName: downloads-series
        - name: plex-movies
          persistentVolumeClaim:
            claimName: downloads-movies
        - name: plex-courses
          persistentVolumeClaim:
            claimName: downloads-courses
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent
  namespace: plex-server
  labels:
    app: qbittorrent
    part-of: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
      part-of: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        part-of: qbittorrent
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:4.4.3
        ports:
        - name: qbittorrent
          containerPort: 8080
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "022"
        volumeMounts:
        - name: qbittorrent
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: qbittorrent
        persistentVolumeClaim:
          claimName: qbittorrent
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-torrents
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: plex-server
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Madrid"
            - name: AUTO_UPDATE
              value: "true"
            - name: RUN_OPTS
              value: ""
          ports:
          - name: jackett
            containerPort: 9117
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jackett-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: plex-server
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Madrid"
          ports:
          - name: sonarr
            containerPort: 8989
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: tv-shows
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: tv-shows
          persistentVolumeClaim:
            claimName: downloads-series
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-torrents
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: plex-server
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Madrid"
          ports:
          - name: radarr
            containerPort: 7878
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: movies
          persistentVolumeClaim:
            claimName: downloads-movies
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-torrents
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-operator
  namespace: plex-server
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - name: plex
          image: ubuntu:24.04
          command: ["/bin/bash", "-c", "while true; do sleep 30; done;"]
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: plex-series
              mountPath: /series
            - name: plex-movies
              mountPath: /movies
            - name: plex-courses
              mountPath: /courses
      volumes:
        - name: plex-series
          persistentVolumeClaim:
            claimName: downloads-series
        - name: plex-movies
          persistentVolumeClaim:
            claimName: downloads-movies
        - name: plex-courses
          persistentVolumeClaim:
            claimName: downloads-courses
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-torrents