---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: plex-server
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: jaymoulin/plex:1.30.1.6562
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-data
              mountPath: /data
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-pvc-config
        - name: plex-data
          persistentVolumeClaim:
            claimName: plex-pvc-datatest
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent
  namespace: plex-server
  labels:
    app: qbittorrent
    part-of: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
      part-of: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        part-of: qbittorrent
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:4.4.3
        ports:
        - name: qbittorrent
          containerPort: 8080
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "022"
        volumeMounts:
        - name: qbittorrent
          mountPath: /config
        - name: downloads-movies
          mountPath: /downloads/movies
        - name: downloads-series
          mountPath: /downloads/series
        resources:
          limits:
            memory: 250Mi
          requests:
            memory: 200Mi
      volumes:
      - name: qbittorrent
        persistentVolumeClaim:
          claimName: qbittorrent
      - name: downloads-series
        persistentVolumeClaim:
          claimName: downloads-series
      - name: downloads-movies
        persistentVolumeClaim:
          claimName: downloads-movies
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: plex-server
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          env:
            - name: PUID
              value: "1000" # Cambia según el UID del usuario
            - name: PGID
              value: "1000" # Cambia según el GID del grupo
            - name: TZ
              value: "Europe/Madrid"
            - name: AUTO_UPDATE
              value: "true" # Opcional
            - name: RUN_OPTS
              value: "" # Opcional
          ports:
          - name: jackett
            containerPort: 9117
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jackett-config