---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-server-qbittorrent-cert
  namespace: plex-server
spec:
  secretName: plex-server-qbittorrent-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - qbittorrent.local.perelohome.com