---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-config
  namespace: plex-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent
  namespace: plex-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-series
  namespace: plex-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-movies
  namespace: plex-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jackett-config
  namespace: plex-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-config
  namespace: plex-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-config
  namespace: plex-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-torrents
  namespace: plex-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi