---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: plex-server
spec:
  selector:
    app: qbittorrent
    part-of: qbittorrent
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: qbittorrent
---
apiVersion: v1
kind: Service
metadata:
  name: jackett-service
  namespace: plex-server
spec:
  selector:
    app: jackett
  type: ClusterIP
  ports:
    - port: 9117
      targetPort: jackett
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: plex-server
spec:
  selector:
    app: sonarr
  type: ClusterIP
  ports:
    - port: 8989
      targetPort: sonarr
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: plex-server
spec:
  selector:
    app: radarr
  type: ClusterIP
  ports:
    - port: 7878
      targetPort: radarr
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: plex-server
spec:
  selector:
    app: jellyfin
  type: ClusterIP
  ports:
    - port: 8096
      targetPort: jellyfin