apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-storage
  namespace: openshift-gitops
spec:
  destination:
    namespace: ceph-csi
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/aperello96/perelo-argocd-apps.git
    path: ceph-csi-storage
    targetRevision: HEAD
    helm:
      releaseName: ceph-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false