---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
data:
/*important information do not put the key in base 64 leave it as it is on the ceph cluster */
  key: {Value_of_the_admin}  
type: kubernetes.io/rbd