apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: travelroute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
      - name: cloudflare-ddns
        image: oznu/cloudflare-ddns:latest
        imagePullPolicy: Always
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns
              key: api-token
        - name: ZONE
          value: "tripted.com"
        # - name: SUBDOMAIN
        #   value: "tripted"
        - name: PROXIED
          value: "true"
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 16Mi
      restartPolicy: Always