apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: travelroute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb-service-cluster" # Nombre del servicio de MongoDB
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://mongodb-service-cluster:27017"
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: travelroute
spec:
  type: ClusterIP
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongoexpress-ingress
  namespace: travelroute
spec:
  rules:
  - host: "mongoexpress.local.perelohome.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express-service 
            port:
              number: 8081
  tls:
  - hosts:
    - mongoexpress.local.perelohome.com
    secretName: mongoexpress-server-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongoexpress-server-cert
  namespace: travelroute
spec:
  secretName: mongoexpress-server-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - mongoexpress.local.perelohome.com