---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: mariadb-pro
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          env:
            - name: PMA_HOST
              value: mariadb-service # Nombre del servicio de MariaDB
            - name: PMA_PORT
              value: "3306"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: mariadb-pro
spec:
  selector:
    app: phpmyadmin
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  namespace: mariadb-pro
spec:
  rules:
  - host: "phpmyadmin.local.perelohome.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phpmyadmin-service 
            port:
              number: 80
  tls:
  - hosts:
    - phpmyadmin.local.perelohome.com
    secretName: phpmyadmin-server-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phpmyadmin-server-cert
  namespace: mariadb-pro
spec:
  secretName: phpmyadmin-server-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - phpmyadmin.local.perelohome.com