apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: mariadb-pro
  labels:
    app: mariadb
spec:
  type: LoadBalancer
  selector:
    app: mariadb
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306