---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripted
  namespace: staging-travelroute
  labels:
    app: tripted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripted
  template:
    metadata:
      labels:
        app: tripted
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: tripted
          image: tripted/tripted-app:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: GOOGLE_API_KEY
            - name: VENICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: VENICE_API_KEY
            - name: AVIASALES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: AVIASALES_API_KEY
            - name: TRAVELPAYOUTS_ID
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: TRAVELPAYOUTS_ID
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: MONGODB_URI
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: EMAIL_FROM
            - name: EMAIL_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: EMAIL_SERVER_HOST
            - name: EMAIL_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: EMAIL_SERVER_PASSWORD
            - name: EMAIL_SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: EMAIL_SERVER_PORT
            - name: EMAIL_SERVER_USER
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: EMAIL_SERVER_USER
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GPT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: GPT_API_KEY
            - name: IMPACT_SID
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: IMPACT_SID
            - name: IMPACT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: IMPACT_TOKEN
            - name: NEXT_PUBLIC_TURNSTILE_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: NEXT_PUBLIC_TURNSTILE_SITE_KEY
            - name: NEXT_PUBLIC_UNSPLASH_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: NEXT_PUBLIC_UNSPLASH_ACCESS_KEY
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: NEXTAUTH_SECRET
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: NEXTAUTH_URL
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: OPENAI_API_KEY
            - name: TURNSTILE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-planner-secrets
                  key: TURNSTILE_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: tripted-service
  namespace: staging-travelroute
spec:
  selector:
    app: tripted
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripted-ingress
  namespace: staging-travelroute
spec:
  rules:
  - host: "staging.tripted.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tripted-service
            port:
              number: 3000
  tls:
  - hosts:
    - staging.tripted.com
    secretName: tripted-server-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tripted-server-cert
  namespace: staging-travelroute
spec:
  secretName: tripted-server-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer-tripted
    kind: ClusterIssuer
  dnsNames:
    - staging.tripted.com