---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-password
  namespace: tripted-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: tripted/staging/mongodb
        property: admin-user
