apiVersion: opstreelabs.in/v1alpha1
kind: MongoDBCluster
metadata:
  name: mongodb
  namespace: tripted-staging
spec:
  clusterSize: 3
  kubernetesConfig:
    image: "quay.io/opstree/mongo:v5.0.6"
    imagePullPolicy: IfNotPresent
    securityContext:
      fsGroup: 1001
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  storage:
    accessModes:
      - ReadWriteOnce
    storageSize: 5Gi
    storageClass: rook-ceph-block
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: mongodb-password
      key: password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: tripted-staging
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-database
  namespace: tripted-staging
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-database
  namespace: tripted-staging
subjects:
  - kind: ServiceAccount
    name: mongodb-database
    namespace: tripted-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-database