apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-ca
  namespace: mongodb-test-1
spec:
  secretName: mongodb-test-1-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - mongodb-0..local.perelohome.com
    - mongodb-1..local.perelohome.com
    - mongodb-2..local.perelohome.com
    - db-node-1.local.perelohome.com
    - db-node-2.local.perelohome.com
    - db-node-3.local.perelohome.com