---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongodb-selfsigned-issuer
  namespace: mongodb-test-1
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-test-1-ca
  namespace: mongodb-test-1
spec:
  isCA: true
  commonName: mongodb-test-1-ca
  secretName: mongodb-test-1-ca
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: mongodb-selfsigned-issuer
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongodb-test-1-ca-issuer
  namespace: mongodb-test-1
spec:
  ca:
    secretName: mongodb-test-1-ca

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-test-1-server
  namespace: mongodb-test-1
spec:
  secretName: mongodb-test-1-tls-secret
  # IMPORTANT: Using a CA Issuer makes cert-manager write `ca.crt` into this secret.
  # The MongoDBCommunity operator requires `ca.crt` for `caCertificateSecretRef`.
  issuerRef:
    name: mongodb-test-1-ca-issuer
    kind: Issuer
  dnsNames:
    # Internal pod DNS (StatefulSet + headless service)
    - mongodb-0.mongodb-svc.mongodb-test-1.svc.cluster.local
    - mongodb-1.mongodb-svc.mongodb-test-1.svc.cluster.local
    - mongodb-2.mongodb-svc.mongodb-test-1.svc.cluster.local
    - mongodb-svc.mongodb-test-1.svc.cluster.local
    # External horizons (what clients will use)
    - db-node-1.local.perelohome.com
    - db-node-2.local.perelohome.com
    - db-node-3.local.perelohome.com